### ISSUE TITLE
 opencv4 was not found 

### ISSUE THREAD

**Issue by Gabrielllopes** [Dovyski/setup-opencv-action#2]
I had the following error during execution:

Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv4' found

and this [guy](https://github.com/opencv/opencv/issues/13154#issuecomment-439335340) sugest to include " OPENCV_GENERATE_PKGCONFIG=ON ". But this option was not available on this setup.

So I implemented that, tested and it works. So I will open a pull request with this option in case someone need.

**Comment by Dovyski** [comment]
I am super glad you spotted the problem and issued a pull request to fix it. Thank you very much! ❤️ 
Your PR has been merged, so you should be able to use the new feature as:

```yaml
steps:
- uses: actions/checkout@v2
- uses: Dovyski/setup-opencv-action # no @v1 here!
  with:
    opencv-version: 4.0.0
    GENERATE_PKGCONFIG: ON
```

**Comment by xellDart** [comment]
I use the last version, but I get same error: 

```sh
# pkg-config --cflags  -- opencv4
Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc' to the PKG_CONFIG_PATH environment variable
No package 'opencv4' found
pkg-config: exit status 1
```

My step is:

```yaml
- uses: Dovyski/setup-opencv-action@v1      <---- i cant delete this
- with:        opencv-version: '4.5.1'        
- ENABLE_PRECOMPILED_HEADERS: ON        
- GENERATE_PKGCONFIG: ON
```
